name: ML Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Cache pip packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    
    - name: Check model parameters
      run: |
        python -c "from mnist_classifier.model import MNISTModel; model = MNISTModel(); params = sum(p.numel() for p in model.parameters()); assert params < 25000, f'Model has {params} parameters'"
    
    - name: Train and test model
      run: |
        python -c "from mnist_classifier.train import train; train()"
        pytest tests/ -v
    
    - name: Upload trained model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: models/
        if-no-files-found: error